#!/bin/bash
echo Rebuilding Packages....
cd target/midi-lovense-bridge-1.0-SNAPSHOT
zip -r ../MidiLovenseBridge.app.zip Midi\ Lovense\ Bridge.app/
cd ..
echo Uploading OSX Version...
scp MidiLovenseBridge.app.zip xitiomet@openstatic.org:/var/www/openstatic.org/lovense/MidiLovenseBridge.app.zip
echo Uploading Windows Version...
scp MidiLovenseBridge.exe xitiomet@openstatic.org:/var/www/openstatic.org/lovense/MidiLovenseBridge.exe
echo Uploading JAR Version...
scp midi-lovense-bridge-1.0-SNAPSHOT.jar xitiomet@openstatic.org:/var/www/openstatic.org/lovense/midi-lovense-bridge-1.0-SNAPSHOT.jar
echo Uploading Debian Version...
scp midi-lovense-bridge-1.0-SNAPSHOT.deb xitiomet@openstatic.org:/var/www/openstatic.org/lovense/midi-lovense-bridge-1.0-SNAPSHOT.deb
echo DONE!
